name: Publish NuGet Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update NuGet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"

      # Install GitVersion to automatically create a semantic
      # version from your repository:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      # Run GitVersion (set an ID to later fetch values)
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - run: dotnet build src/blackjack-events-library.sln -c Release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}
      - run: dotnet test src/blackjack-events-library.sln
      - run: dotnet pack src/BlackJack.Events/BlackJack.Events.csproj -c Release -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.Sha }} -p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
      - run: dotnet pack src/BlackJack.Events.Abstractions/BlackJack.Events.Abstractions.csproj -c Release -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.Sha }} -p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: src/BlackJack.Events/bin/Release/*${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package-abstractions
          path: src/BlackJack.Events/bin/Release/*${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg

  deploy-core:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy NuGet Package
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
          path: ./package
      - name: Publish
        run: nuget push package/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

  deploy-abstractions:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy NuGet Package
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package-abstractions
          path: ./package
      - name: Publish
        run: nuget push package/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
